### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ValeC08** [USDA-VS/snp_analysis#13]
Hello,
I'm facing a problem running the first part of vSNP pipeline. 
I have Mycobacterium bovis raw reads obtained from Illumina Miniseq, with a paired end run, and I want the Mycobacterium bovis AF2122 as a reference. I wrote the following command:

SNP_step1.py -r1 47104-2018_S10_L001_R1_001.fastq.gz -r2 47104-2018_S10_L001_R2_001.fastq.gz -r Mycobacterium_AF2122
and the analysis starts properly until I get this message:

Traceback (most recent call last):
  File "/home/valentina.carta@izsler.it/anaconda3/envs/vSNP/bin/vSNP_step1.py", line 122, in <module>
    align_reads.align()
  File "/home/valentina.carta@izsler.it/anaconda3/envs/vSNP/bin/vsnp_alignment_vcf.py", line 376, in align
    group_reporter = GroupReporter(zero_coverage_vcf, ref_option)
  File "/home/valentina.carta@izsler.it/anaconda3/envs/vSNP/bin/vsnp_group_reporter.py", line 30, in __init__
    defsnp_iterator = iter(defining_snps.iteritems())
  File "/home/valentina.carta@izsler.it/anaconda3/envs/vSNP/lib/python3.9/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'iteritems'

After that anything happen and my folder look like this:
![image](https://github.com/USDA-VS/vSNP/assets/120626347/b2bc5d72-4cb7-4547-a3d8-e2497eb0133f)
Sometimes it happen that the command line write itself this: Minimum k-mer coverage is 7 
and keep going into the analysis (?), but not always. 

How can I solve this problem?

Hope I wrote clearly,
thank you in advance
Valentina

**Comment by stuber** [comment]
Hi Valentina, thanks for the question.

vSNP3 is the latest version of vSNP. Please give this a try following the instructions here:

https://github.com/USDA-VS/vSNP3

It appears that iteritems no longer works with pandas >2.0. The build script for vSNP likely isn't specifying the pandas version. The vSNP3 build script specifies the pandas version, so building with a new conda environment for vSNP3 should fix the error.

The outputted VCFs, tables, and trees will be the same for vSNP3 as with vSNP. The output from the two versions is organized slightly differently, and vSNP3 has updated options available, but the overall results will be the same for both. However, only vSNP3 is currently being maintained.

Tod

**Comment by ValeC08** [comment]
Hi Tod,
following your advice I used the latest version.
I faced a problem and I attach here the command line:

![Screenshot from 2023-06-22 11-00-09](https://github.com/USDA-VS/vSNP/assets/120626347/488f50ac-cecf-42e3-ae8f-de58b974215f)

Since the problem was a variable-type conversion and I think it's just an information printed into my final report, I just commented the line involved (line 119) and the process went well (I suppose).
That's what I got at the end, is it right?

![Screenshot from 2023-06-22 11-05-52](https://github.com/USDA-VS/vSNP/assets/120626347/e66eeed9-9dcf-4bf3-9169-b26d03388cad)

Thank you in advance
Valentina

**Comment by stuber** [comment]
Thank you for the update. I'm glad to hear that it is working fine except for the error displayed. You're correct that the error is only in the final PDF report.

The formatting error seems to be caused by seqkit. I'm wondering if an updated version of seqkit added a thousand comma delimiter. I should remove this with an update. If possible, could you please share the version of seqkit you're currently running?

To check the version of seqkit, you can use the following command:

`seqkit version`

**Comment by ValeC08** [comment]
Of course!
Seqkit version in 2.4.0

**Comment by stuber** [comment]
Excellent!

At a glance, I don't see anything specific about a thousand delimiter in the seqkit version notes, but I'm going to assume that this is the issue since I'm using an older version, v0.16.0. I will test it and make the necessary updates in the next vSNP3 release.  Thanks!
